### ISSUE TITLE
Reduce MetadataSpec's flakiness

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-scala-tracker#110]
It seems travis sometimes doesn't get the expected result: https://travis-ci.org/snowplow/snowplow-scala-tracker/jobs/436011353#L972

**Comment by istreeter** [comment]
The old tests assumed that the endpoints (e.g. `http://169.254.169.254/latest/dynamic/instance-identity/document/`) are not accessible when the tests run.  So they asserted that you get a connection timeout.

But this is flawed - depending on the runtime environment.  For example, in github actions that endpoint 👆 returns a html page.

The solution is to mock the http client in the tests, rather than relying on real http requests.
