### ISSUE TITLE
Replace UUIDProvider by fuuid

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-scala-tracker#112]
https://github.com/ChristopherDavenport/fuuid

**Comment by JackTreble** [comment]
I'll take this ☺

**Comment by flevour** [comment]
@JackTreble any update on this?

**Comment by JackTreble** [comment]
@flevour Linked the pull request

**Comment by istreeter** [comment]
I see one problem with FUUID: in order to call [FUUID.randomUUID](https://github.com/ChristopherDavenport/fuuid/blob/master/modules/core/src/main/scala/io/chrisdavenport/fuuid/FUUID.scala#L49) we need to provide a `Sync[F]` as an evidence parameter.  This does not work nicely for the id-emitters, because there is no such `Sync[Id]`.  It is important to maintain the id-emitters for users who do not want to work with effect types.

I propose we provide our own implicit UUIDProvider instances for the common effect types (Id and Sync), and abandon the idea to use FUUID.
